### ISSUE TITLE
Exception while runing  Main class

### ISSUE THREAD

**Issue by Nav15** [naishe/mastering-cassandra-v2#1]
Hi,

Getting below exception while running the Main class from Eclispe:

2017-01-06 15:35:44 WARN FrameCompressor:44 - Cannot find Snappy class, you should make sure the Snappy library is in the classpath if you intend to use it. Snappy compression will not be available for the protocol.
2017-01-06 15:35:44 WARN FrameCompressor:87 - Cannot find LZ4 class, you should make sure the LZ4 library is in the classpath if you intend to use it. LZ4 compression will not be available for the protocol.
2017-01-06 15:35:44 FATAL Main:246 - Something went wrong, please look into the stacktrace here:
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:223)
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1230)
at com.datastax.driver.core.Cluster.init(Cluster.java:157)
at com.datastax.driver.core.Cluster.connect(Cluster.java:245)
at in.naishe.simpleBlog.CassandraConnection.getSession(CassandraConnection.java:23)
at in.naishe.simpleBlog.Main.setup(Main.java:100)
at in.naishe.simpleBlog.Main.main(Main.java:238)

Note: Cassandra is running ($CASSANDRA_HOME/bin cassandra -f) in backend at:
INFO 10:01:57 Starting listening for CQL clients on localhost/127.0.0.1:9042 (unencrypted)...

**Comment by alxp** [comment]
Hi @Nav15 , I had the same issue, and upon searching found that it was because I was running Cassandra 3. Cassandra 3 has an updated schema for representing tables which is incompatible with the version of the driver called for in simpleBlog's pom.xml file.

I've forked this project and updated the Chapter 1 code to work with Cassandra version 3.1. This also involved changing how the blog class handles dates - changing from long to java.util.Date.

https://github.com/alxp/mastering-cassandra-v2/tree/Cassandra3
